name: build
on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux_noble:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install system dependencies (webkit 4.1)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config build-essential curl wget file \
            libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev \
            libwebkit2gtk-4.1-dev libsoup2.4-dev

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Build
        run: npm run tauri build -- -v

      - name: Prepare ZIP
        run: |
          cd src-tauri/target/release
          zip -r gmpublisher_linux64.zip gmpublisher libsteam_api.so

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/target/release/gmpublisher_linux64.zip
          fail_on_unmatched_files: true
